version: '3.8'

services:
  bot:
    image: ghcr.io/catofsof/vk-unsilence:latest
    command: npm run start:prod
    volumes:
      - audio:/usr/src/app/audio
    secrets:
      - source: vk-unsilence-secrets
        target: vk-unsilence-secrets.yml

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data

volumes:
  audio:
  redis_data:

secrets:
  vk-unsilence-secrets:
    external: true
